version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  build_docker_image:
    executor: python-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Get Date Tag
          command: 
            echo "export DATE_TAG=$(date +'%Y-%m-%d')" >> $BASH_ENV

      - run:
          name: Build Docker Image
          command: 
            source $BASH_ENV
            docker build -t $DOCKERHUB_USERNAME/flask-app:$DATE_TAG .

      - run:
          name: Authenticate 
          command: 
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Push Docker Image
          command: 
            source $BASH_ENV
            docker push $DOCKERHUB_USERNAME/flask-app:$DATE_TAG

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image