version: 2.1

orbs:
  teams-notifier: atharva17/teams-notifier@1.0.0
  echo-orb: atharva17/echo-orb@1.0.0
  
jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$(date +'%Y%m%d')
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      - echo-orb

      - teams-notifier/notify_teams_status:
          title: "Build Docker Image"
          image-tag: "${IMAGE_TAG}"

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image