version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  build_docker_image:
    executor: python-executor
    steps:
      - checkout

      - setup_remote_docker


      - run:
          name: Build Docker Image
          command: 
            docker build -t $DOCKERHUB_USERNAME/flask-app:latest .

      - run:
          name: Authenticate 
          command: 
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Push Docker Image
          command: 
            docker push $DOCKERHUB_USERNAME/flask-app:latest

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image