version: 2.1

orbs:
  teams-notifier: atharva17/teams-notifier@1.0.0

jobs:
  build-push-to-dockerhub:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      # - run:
      #     name: Notify GitHub (running)
      #     command: |
      #       curl -X POST https://api.github.com/repos/atharvarokade17/flask-docker-ci/dispatches \
      #         -H "Accept: application/vnd.github+json" \
      #         -H "Authorization: Bearer $GITHUB_TOKEN" \
      #         -d '{
      #           "event_type": "circleci-status",
      #           "client_payload": {
      #             "status": "running",
      #             "branch": "'"$CIRCLE_BRANCH"'"
      #           }
      #         }'

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$(date +'%Y%m%d')
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      - teams-notifier/notify_teams_status:
          title: "Build Docker Image"
          image-tag: "${IMAGE_TAG}"

  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Hello World
          command: echo "Hello, World!"        

workflows:
  version: 2
  dev-workflow:
    jobs:
      - build-push-to-dockerhub:
          filters:
            branches:
              only:
                - dev

  main-workflows:
    jobs:
      - build-push-to-dockerhub:
          filters:
            branches:
              only:
                - main
      - hold:
          type: approval
          requires:
            - build-push-to-dockerhub
      - hello-world:
          requires:
            - hold
            