version: 2.1

commands:
  notify_teams_status:
    parameters:
      job_name:
        type: string
        default: "Job"
      success_message:
        type: string
        default: "Job succeeded."
      failure_message:
        type: string
        default: "Job failed."
    steps:
      - notify_teams:
          status: "Success"
          color: "00FF00"
          title: "✅ << parameters.job_name >> Succeeded"
          message: "<< parameters.success_message >>"
          condition: on_success

      - notify_teams:
          status: "Failed"
          color: "FF0000"
          title: "❌ << parameters.job_name >> Failed"
          message: "<< parameters.failure_message >>"
          condition: on_fail

  notify_teams:
    parameters:
      status:
        type: string
      color:
        type: string
      title:
        type: string
      message:
        type: string
      condition:
        type: string
        default: "always"
    steps:
      - run:
          name: Notify Microsoft Teams (<< parameters.status >>)
          when: << parameters.condition >>
          command: |
            curl -H 'Content-Type: application/json' -d "{
              \"@type\": \"MessageCard\",
              \"@context\": \"http://schema.org/extensions\",
              \"summary\": \"<< parameters.status >>\",
              \"themeColor\": \"<< parameters.color >>\",
              \"title\": \"<< parameters.title >>\",
              \"sections\": [
                {\"text\": \"**Project**  ${CIRCLE_PROJECT_REPONAME}\"},
                {\"text\": \"**Job Number**  ${CIRCLE_BUILD_NUM}\"},
                {\"text\": \"**Branch**  ${CIRCLE_BRANCH}\"},
                {\"text\": \"**Repository**  ${IMAGE_NAME}\"},
                {\"text\": \"**Message**  << parameters.message >>\"}
              ],
              \"potentialAction\": [
                {
                  \"@type\": \"OpenUri\",
                  \"name\": \"View Job in CircleCI\",
                  \"targets\": [{ \"os\": \"default\", \"uri\": \"${CIRCLE_BUILD_URL}\" }]
                }
              ]
            }" $TEAMS_WEBHOOK_URL

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$(date +'%Y%m%d')
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG
      - notify_teams_status:

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image