version: 2.1

orbs:
  teams-notifier: atharva17/teams-notifier@1.0.0

jobs:
  build-push-to-dockerhub:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$(date +'%Y%m%d')
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .

      # 🔒 Trivy Scan (Dockerized)
      - run:
          name: Scan Docker Image with Trivy
          command: |
            source $BASH_ENV
            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v $PWD:/workspace \
              aquasec/trivy:0.69.3 image \
              --format json \
              --output trivy-report.json \
              $IMAGE_NAME:$IMAGE_TAG

      # 📦 Store report
      - store_artifacts:
          path: trivy-report.json
          destination: trivy-report

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      - teams-notifier/notify_teams_status:
          title: "Build Docker Image"
          image-tag: "${IMAGE_TAG}"

  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Hello World
          command: echo "Hello, World!"        

workflows:
  version: 2

  dev-workflow:
    jobs:
      - build-push-to-dockerhub:
          filters:
            branches:
              only:
                - dev

  prod-workflows:
    jobs:
      - build-push-to-dockerhub:
          filters:
            branches:
              only:
                - main
      - hold:
          type: approval
          requires:
            - build-push-to-dockerhub
      - hello-world:
          requires:
            - hold