version: 2.1

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$(date +'%Y%m%d')
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      # Single Teams notification for both success and failure
      - run:
          name: Notify Microsoft Teams
          command: |
            set +e  # Allow the script to continue even if previous steps failed
            if [ "$CIRCLE_JOB" == "build_docker_image" ]; then
              STATUS="success"
              COLOR="0076D7"
              TITLE="✅ Docker Image Built & Pushed"
              MESSAGE="Docker image ${IMAGE_NAME}:${IMAGE_TAG} built & pushed"
            fi

            if [ "${CIRCLE_JOB_STATUS}" != "success" ]; then
              STATUS="failure"
              COLOR="FF0000"
              TITLE="❌ Docker Build Failed"
              MESSAGE="Docker build failed"
            fi

            curl -H 'Content-Type: application/json' \
              -d "{
                    \"@type\": \"MessageCard\",
                    \"@context\": \"http://schema.org/extensions\",
                    \"summary\": \"Docker Build Notification\",
                    \"themeColor\": \"$COLOR\",
                    \"title\": \"$TITLE\",
                    \"sections\": [{
                      \"activityTitle\": \"${CIRCLE_PROJECT_REPONAME}\",
                      \"activitySubtitle\": \"Build #${CIRCLE_BUILD_NUM} on branch ${CIRCLE_BRANCH}\",
                      \"facts\": [
                        {\"name\": \"Message\", \"value\": \"$MESSAGE\"},
                        {\"name\": \"Commit\", \"value\": \"${CIRCLE_SHA1}\"}
                      ]
                    }]
                  }" \
              $TEAMS_WEBHOOK_URL

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image