version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4.1
  aws-s3: circleci/aws-s3@4.1.2

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable  
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app-image .

      - run:
          name: Save and Compress Docker Image
          command: |
            docker save my-app-image | gzip > my-app-image.tar.gz

      - aws-cli/setup:
           profile-name: default
           
      - aws-s3/copy:
          from: my-app-image.tar.gz
          to: s3://my-app-artifacts/my-app-image-<< pipeline.git.revision >>.tar.gz
          arguments: |
            --acl private

workflows:
  version: 2
  build:
    jobs:
      - build-and-push