version: 2.1

parameters:
  image_tag_date:
    type: string
    default: ""

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  build_docker_image:
    executor: python-executor
    parameters:
      image_tag_date:
        type: string
        default: ""
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image with dynamic date tag
          command: |
            if [ -z "<< parameters.image_tag_date >>" ]; then
              IMAGE_TAG=$(date +'%Y%m%d')
            else
              IMAGE_TAG="<< parameters.image_tag_date >>"
            fi
            echo "Using image tag: $IMAGE_TAG"
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image:
          image_tag_date: "<< pipeline.parameters.image_tag_date >>"