version: 2.1

parameters:
  image_tag_date:
    type: string
    default: ""

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    parameters:
      image_tag_date:
        type: string
        default: ""
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image with dynamic date tag
          command: |
            if [ -z "<< parameters.image_tag_date >>" ]; then
              IMAGE_TAG=$(date +'%Y%m%d')
            else
              IMAGE_TAG="<< parameters.image_tag_date >>"
            fi
            echo "Using image tag: $IMAGE_TAG"
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      - run:
          name: Notify Microsoft Teams on success
          command: |
            source $BASH_ENV
            curl -H 'Content-Type: application/json' \
              -d "{
                    \"@type\": \"MessageCard\",
                    \"@context\": \"http://schema.org/extensions\",
                    \"summary\": \"CircleCI Docker Build\",
                    \"themeColor\": \"0076D7\",
                    \"title\": \"✅ Docker Image Built & Pushed\",
                    \"sections\": [{
                      \"activityTitle\": \"${CIRCLE_PROJECT_REPONAME}\",
                      \"activitySubtitle\": \"Build #${CIRCLE_BUILD_NUM} on branch ${CIRCLE_BRANCH}\",
                      \"facts\": [
                        {\"name\": \"Image\", \"value\": \"${IMAGE_NAME}:${IMAGE_TAG}\"},
                        {\"name\": \"Commit\", \"value\": \"${CIRCLE_SHA1}\"}
                      ]
                    }]
                  }" \
              $TEAMS_WEBHOOK_URL

      - run:
          name: Notify Microsoft Teams on failure
          when: on_fail
          command: |
            curl -H 'Content-Type: application/json' \
              -d "{
                    \"@type\": \"MessageCard\",
                    \"@context\": \"http://schema.org/extensions\",
                    \"summary\": \"CircleCI Docker Build\",
                    \"themeColor\": \"FF0000\",
                    \"title\": \"❌ Docker Build Failed\",
                    \"sections\": [{
                      \"activityTitle\": \"${CIRCLE_PROJECT_REPONAME}\",
                      \"activitySubtitle\": \"Build #${CIRCLE_BUILD_NUM} on branch ${CIRCLE_BRANCH}\"
                    }]
                  }" \
              $TEAMS_WEBHOOK_URL

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image:
          image_tag_date: "<< pipeline.parameters.image_tag_date >>"