version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: my-app-image
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t ${IMAGE_NAME}:<< pipeline.git.revision >> .

      - run:
          name: Save and Compress Docker Image
          command: |
            docker save ${IMAGE_NAME}:<< pipeline.git.revision >> | gzip > ${IMAGE_NAME}-<< pipeline.git.revision >>.tar.gz

      - aws-s3/copy:
          from: ${IMAGE_NAME}-<< pipeline.git.revision >>.tar.gz
          to: s3://my-app-artifacts/${IMAGE_NAME}-<< pipeline.git.revision >>.tar.gz
          arguments: |
            --acl private

workflows:
  version: 2
  build:
    jobs:
      - build-and-push