version: 2.1

parameters:
  image_tag_date:
    type: string
    default: ""

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image with dynamic date tag
          command: |
            if [ -z "<< parameters.image_tag_date >>" ]; then
              IMAGE_TAG=$(date +'%Y%m%d')
            else
              IMAGE_TAG="<< parameters.image_tag_date >>"
            fi
            echo "Using image tag: $IMAGE_TAG"
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      - run:
          name: Notify Microsoft Teams
          when: always
          command: |
            source $BASH_ENV
            BUILD_URL="https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM"
            COMMIT_MSG=$(git log -1 --pretty=%B)
            AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')

            PAYLOAD=$(cat <<EOF
            {
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "themeColor": "0076D7",
              "summary": "Docker Build Notification",
              "sections": [{
                "activityTitle": "**SUCCESS** flask-docker-ci #$CIRCLE_BUILD_NUM",
                "facts": [
                  { "name": "Job", "value": "$CIRCLE_JOB" },
                  { "name": "Branch", "value": "$CIRCLE_BRANCH" },
                  { "name": "Author", "value": "$AUTHOR_EMAIL" },
                  { "name": "Commit", "value": "$CIRCLE_SHA1" },
                  { "name": "Message", "value": "✅ Docker image $IMAGE_NAME:$IMAGE_TAG has been built and pushed successfully." },
                  { "name": "Commit Message", "value": "$COMMIT_MSG" }
                ],
                "markdown": true
              }],
              "potentialAction": [{
                "@type": "OpenUri",
                "name": "View Pipeline",
                "targets": [{ "os": "default", "uri": "$BUILD_URL" }]
              }]
            }
            EOF
            )

            curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image:
          image_tag_date: "<< pipeline.parameters.image_tag_date >>"