version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  build_docker_image:
    executor: python-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Set dynamic tag
          command: 
            echo "export IMAGE_TAG=$(date +'%Y%m%d')" >> $BASH_ENV
      - run:
          name: Authenticate with DockerHub
          command: 
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: 
            source $BASH_ENV
            docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: 
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image