version: 2.1

parameters:
  image_tag_date:
    type: string
    default: ""

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    parameters:
      image_tag_date:
        type: string
        default: ""
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image with dynamic date tag
          command: |
            if [ -z "<< parameters.image_tag_date >>" ]; then
              IMAGE_TAG=$(date +'%Y%m%d')
            else
              IMAGE_TAG="<< parameters.image_tag_date >>"
            fi
            echo "Using image tag: $IMAGE_TAG"
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      - run:
          name: Notify Microsoft Teams
          when: always
          command: |
            source $BASH_ENV

            # Default to FAILURE
            STATUS="FAILURE"
            if [ "$CIRCLE_JOB" = "build_docker_image" ] && [ $? -eq 0 ]; then
              STATUS="SUCCESS"
            fi

            BUILD_NUM="#${CIRCLE_BUILD_NUM}"
            JOB_NAME="$CIRCLE_JOB"
            BRANCH="$CIRCLE_BRANCH"
            AUTHOR="$CIRCLE_USERNAME"
            SHORT_SHA=$(echo $CIRCLE_SHA1 | cut -c1-7)
            COMMIT_MSG=$(git log -1 --pretty=%B $CIRCLE_SHA1)

            # Teams requires escaped newlines (\\n)
            MESSAGE="${STATUS} flask-docker-ci ${BUILD_NUM}\\nJob\\n${JOB_NAME}\\nBranch\\n${BRANCH}\\nAuthor\\n${AUTHOR}\\nCommit ${SHORT_SHA}\\nMessage\\nDocker image *$IMAGE_NAME:$IMAGE_TAG* has been built and pushed successfully.\\n${COMMIT_MSG}"
            PAYLOAD="{\"text\": \"$MESSAGE\"}"

            curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image:
          image_tag_date: "<< pipeline.parameters.image_tag_date >>"