version: 2.1

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$(date +'%Y%m%d')
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .

      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG

      # Success notification (green theme)
      - run:
          name: Notify Microsoft Teams on success
          command: |
            curl -H 'Content-Type: application/json' \
              -d "{
                    \"@type\": \"MessageCard\",
                    \"@context\": \"http://schema.org/extensions\",
                    \"summary\": \"Docker Build Success\",
                    \"themeColor\": \"00FF00\",
                    \"title\": \"✅ Docker Build Success\",
                    \"text\": \"Project ${CIRCLE_PROJECT_REPONAME}\nJob Number ${CIRCLE_BUILD_NUM}\"
                  }" \
              $TEAMS_WEBHOOK_URL

      # Failure notification (red theme)
      - run:
          name: Notify Microsoft Teams on failure
          when: on_fail
          command: |
            curl -H 'Content-Type: application/json' \
              -d "{
                    \"@type\": \"MessageCard\",
                    \"@context\": \"http://schema.org/extensions\",
                    \"summary\": \"Docker Build Failed\",
                    \"themeColor\": \"FF0000\",
                    \"title\": \"❌ Docker Build Failed\",
                    \"text\": \"Project ${CIRCLE_PROJECT_REPONAME}\nJob Number ${CIRCLE_BUILD_NUM}\"
                  }" \
              $TEAMS_WEBHOOK_URL

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image