version: 2.1

commands:
  notify_teams:
    parameters:
      status:
        type: string
      color:
        type: string
      title:
        type: string
      condition:
        type: string
        default: "always"
      image-tag:
        type: string
        default: "latest"
    steps:
      - run:
          name: Notify Microsoft Teams (<< parameters.status >>)
          when: << parameters.condition >>
          command: |
            curl -H 'Content-Type: application/json' -d "{
              \"@type\": \"MessageCard\",
              \"@context\": \"http://schema.org/extensions\",
              \"summary\": \"<< parameters.status >>\",
              \"themeColor\": \"<< parameters.color >>\",
              \"title\": \"<< parameters.title >>\",
              \"sections\": [
                {\"text\": \"**Project**  ${CIRCLE_PROJECT_REPONAME}\"},
                {\"text\": \"**Branch**  ${CIRCLE_BRANCH}\"},
                {\"text\": \"**Tag**  << parameters.image-tag >>\"}
              ],
              \"potentialAction\": [
                {
                  \"@type\": \"OpenUri\",
                  \"name\": \"View Job in CircleCI\",
                  \"targets\": [
                    { \"os\": \"default\", \"uri\": \"${CIRCLE_BUILD_URL}\" }
                  ]
                }
              ]
            }" $TEAMS_WEBHOOK_URL

  notify_teams_status:
    parameters:
      title:
        type: string
        default: $CIRCLE_JOB
      image-tag:
        type: string
        default: "latest"
    steps:
      - notify_teams:
          status: "Success"
          color: "00FF00"
          title: "✅ << parameters.title >> Succeeded"
          condition: on_success
          image-tag: "<< parameters.image-tag >>"

      - notify_teams:
          status: "Failed"
          color: "FF0000"
          title: "❌ << parameters.title >> Failed"
          condition: on_fail
          image-tag: "<< parameters.image-tag >>"

  notify_on_hold:
    steps:
      - notify_teams:
          status: "On Hold"
          color: "FFFF00"
          title: "⏸️ Workflow is waiting for manual approval before deploy"
          condition: always

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=$(date +'%Y%m%d')
            echo "export IMAGE_TAG=$IMAGE_TAG" >> $BASH_ENV
            docker build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker push $IMAGE_NAME:$IMAGE_TAG
      - notify_teams_status:
          title: "Build Docker Image"
          image-tag: "${IMAGE_TAG}"

  deploy_app:
    docker:
      - image: cimg/base:stable
    steps:
      - notify_on_hold 
      - run:
          name: Deploy application
          command: |
            echo "🚀 Deploying application..."
      - notify_teams_status:
          title: "Deploy Application"
          image-tag: "latest"

workflows:
  version: 2
  docker_build:
    jobs:
      - build_docker_image
      - hold_for_approval:
          type: approval
          requires:
            - build_docker_image
      - deploy_app:
          requires:
            - hold_for_approval
