version: 2.1

parameters:
  image_tag:
    type: string
    default: ""  # Optional: You can leave this blank and handle it in the job

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  build_and_push:
    executor: python-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build and Push Docker Image
          command: |
            IMAGE_NAME="your-dockerhub-username/your-repo-name"
            if [ -z "<< pipeline.parameters.image_tag >>" ]; then
              IMAGE_TAG=$(date +'%Y%m%d')
            else
              IMAGE_TAG="<< pipeline.parameters.image_tag >>"
            fi

            echo "Using tag: $IMAGE_TAG"

            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_push